import psycopg2 
conn = psycopg2.connect(host='localhost', port=5432, dbname='fastapi', user='postgres', password='Cristiano@710') 
cur = conn.cursor() 
cur.execute("ALTER TABLE posts ADD COLUMN test_col VARCHAR") 
conn.commit() 
cur.execute("SELECT column_name FROM information_schema.columns WHERE table_name='posts'") 
print('same connection:', cur.fetchall()) 
cur.close() 
conn.close() 
conn2 = psycopg2.connect(host='localhost', port=5432, dbname='fastapi', user='postgres', password='Cristiano@710') 
cur2 = conn2.cursor() 
cur2.execute("SELECT column_name FROM information_schema.columns WHERE table_name='posts'") 
