import psycopg2 
conn = psycopg2.connect(host='localhost', port=5432, dbname='fastapi', user='postgres', password='Cristiano@710') 
cur = conn.cursor() 
cur.execute("CREATE TABLE users (id SERIAL PRIMARY KEY, email VARCHAR NOT NULL UNIQUE, password VARCHAR NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now())") 
conn.commit() 
cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='public'") 
print('same connection:', cur.fetchall()) 
cur.close() 
conn.close() 
conn2 = psycopg2.connect(host='localhost', port=5432, dbname='fastapi', user='postgres', password='Cristiano@710') 
cur2 = conn2.cursor() 
cur2.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='public'") 
print('fresh connection:', cur2.fetchall()) 
